GET http://localhost:4004/catalog/Authors

###
GET http://localhost:4004/catalog/Authors?$expand=books

###
GET http://localhost:4004/catalog/Books

###
GET http://localhost:4004/catalog/Books?$expand=author

###
GET http://localhost:4004/catalog/Orders

###
POST http://localhost:4004/catalog/Authors
Content-Type: application/json

{"ID": 4711, "name": "Max Streifeneder"}

###
POST http://localhost:4004/catalog/Authors
Content-Type: application/json

{"ID": 4712, "name": "Max Streifeneder"}

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{"ID": 999, "title": "Java rocks", "stock": 10, "author_ID": 4711}

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{"ID": 1000, "title": "Java rocks", "stock": 10, "author_ID": 4711}